version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./images:/app/images
      - ./Brain_Tumor_EHR_Clean_1000.xlsx:/app/Brain_Tumor_EHR_Clean_1000.xlsx
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=divya1936
      - DB_NAME=brain_tumor_ehr
    depends_on:
      - mysql
    networks:
      - ehr-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ehr-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: divya1936
      MYSQL_DATABASE: brain_tumor_ehr
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ehr-network

volumes:
  mysql_data:

networks:
  ehr-network:
    driver: bridge